spring:
  application:
    name: bookstore

spring:
  h2:
    console:
      enabled:true
  datasource:
    url: jdb:h2:mem:testdb
    username: im
    password: hmd
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yaml